method: bayes               
metric:
  name: multi_objective_metric  
  goal: minimize           
parameters:
  clip_eps:
    min: 0.06
    max: 0.16
  vf_coeff:
    min: 0.11
    max: 0.22
  ent_coeff:
    min: 0.05
    max: 0.15
  reward_fail_to_service_goal_larger_index:
    min: -0.8
    max: -0.3
  individual_reward_weight:
    min: 0.2
    max: 0.7
  reward_exceed_horizon:
    min: -5.0
    max: -2.0
  