method: bayes               
metric:
  name: multi_objective_metric 
  goal: minimize           
parameters:
  clip_eps:
    min: 0.05
    max: 0.18
  vf_coeff:
    min: 0.1
    max: 0.25
  ent_coeff:
    min: 0.05
    max: 0.25
  reward_fail_to_service_goal_larger_index:
    min: -0.8
    max: -0.2
  individual_reward_weight:
    min: 0.3
    max: 1.0
  reward_exceed_horizon:
    min: -2
    max: -5
  