method: bayes               
metric:
  name: average_competitive_ratio    
  goal: minimize           
parameters:
  clip_eps:
    min: 0.05
    max: 0.2
  vf_coeff:
    min: 0.05
    max: 0.23
  ent_coeff:
    min: 0.05
    max: 0.25
  optimizer_norm_clip:
    min: 1.0
    max: 5.0
  reward_fail_to_service_goal_larger_index:
    min: -0.8
    max: -0.2
  individual_reward_weight:
    min: 0.3
    max: 1.0
  