method: bayes               
metric:
  name: average_competitive_ratio    
  goal: minimize           
parameters:
  clip_eps:
    min: 0.05
    max: 0.25
  vf_coeff:
    min: 0.05
    max: 0.25
  ent_coeff:
    min: 0.05
    max: 0.25
  reward_fail_to_service_goal_larger_index:
    min: -1.0
    max: -0.1
  optimizer_norm_clip:
    min: 0.5
    max: 10
  individual_reward_weight:
    min: 0.0
    max: 1.0
  num_critic_values:
    values: [1, 2]
  anneal_individual_reward_weight:
    values: ["constant", "linear"]
  